name: encrypt-passwords
on: issues
jobs:
  encryption:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          java-package: 'jdk'

      - name: Install Springboot CLI
        run: |
          wget https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.5.5/spring-boot-cli-2.5.5-bin.tar.gz
          tar -zxvf spring-boot-cli-2.5.5-bin.tar.gz
          export PATH=$PATH:$pwd/spring-2.5.5/bin

      - name: Verify SpringBoot CLI Installation
        run: |
          spring --version

      - name: encrypt
        run: |
          spring encrypt "Hello" --key 'ABC'
