name: encrypt-passwords
on: issues
jobs:
  encryption:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          java-package: 'jdk'

      - name: Install SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version

      - name: Install Springboot CLI
        run: |
          sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-2.1.0.M3-bin/spring-2.1.0.M3/
          sdk default springboot dev
          spring --version

      # - name: Install Springboot CLI
      #   run: |
      #     curl -s "https://get.sdkman.io" | bash
      #     source "$HOME/.sdkman/bin/sdkman-init.sh"
      #     sdk install springboot


      # - name: encrypt
      #   run: |
      #     spring encrypt "Hello" --key 'ABC'
