name: encrypt
on: 
  workflow_call:
    inputs:
      password:
        required: true
        type: string
    outputs:
      encrypted-pass:
        description: "Encrypted password"
        value: ${{ jobs.encrypt.outputs.encrypted-pass }}
jobs:
  encrypt:
    runs-on: ubuntu-latest
    outputs:
      encrypted-pass: ${{ steps.encrypt-pass.outputs.encrypted-pass }}
    steps:

      - name: Get Password
        run: |
          PASS=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASS
          echo PASS=$PASS >> $GITHUB_ENV

      - name: Install Java8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          java-package: 'jdk'
      
      - name: Install SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          # source "$HOME/.sdkman/bin/sdkman-init.sh"
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk version
          sdk list springboot

      - name: Install Springboot CLI
        id: encrypt-pass
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install springboot 2.0.1
          spring --version
          spring install org.springframework.cloud:spring-cloud-cli:1.3.2.RELEASE
          echo "==========encypting========="
          encrypted_pass=$(spring encrypt "${{ env.PASS }}" --key 'ABC')
          echo encrypted-pass=$encrypted_pass >> $GITHUB_OUTPUT
